### ISSUE TITLE
Crash when import the package

### ISSUE THREAD

**Issue by kyungeonchoi** [iris-hep/func_adl_servicex#35]
Hi @gordonwatts, could you have a look the following error? Import the package just after installation doesn't work.

```
...
Successfully installed func-adl-servicex-1.1.2 idna-2.10 qastle-0.11.0 servicex-2.4
(base) KE-MBP:servicex-access-examples kchoi$ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import func_adl_servicex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/func_adl_servicex/__init__.py", line 3, in <module>
    from .ServiceX import ServiceXSourceUpROOT, ServiceXSourceXAOD, ServiceXSourceCMSRun1AOD, FuncADLServerException  # NOQA
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/func_adl_servicex/ServiceX.py", line 10, in <module>
    from servicex import ServiceXDataset
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/__init__.py", line 1, in <module>
    from .servicex import ServiceXDataset, StreamInfoUrl, StreamInfoPath  # NOQA
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 15, in <module>
    from servicex.servicex_config import ServiceXConfigAdaptor
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex_config.py", line 7, in <module>
    from .utils import ServiceXException
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/utils.py", line 467, in <module>
    from backoff._common import (  # noqa: E402
ImportError: cannot import name '_prepare_logger' from 'backoff._common' (/Users/kchoi/anaconda3/lib/python3.7/site-packages/backoff/_common.py)
>>>
```

**Comment by kyungeonchoi** [comment]
It seems like you are missing the following requirement for the `backoff` package in the `setup.py`.
```
pip install backoff>=1.11.1
```
It works with the latest version of `backoff`.

**Comment by gordonwatts** [comment]
Ah - yeah - that is it. I encountered that the other day. Thanks for reminding me that needs to get fixed!

**Comment by gordonwatts** [comment]
Fixed in the underlying `servicex` package.
